// Parses the jira_story string generated by synthesis into structured fields.
// Defensive: missing sections produce empty strings/arrays rather than throwing.

export interface ParsedJiraStory {
  title: string;
  userStory: string;
  context: string;
  acceptanceCriteria: string[];
}

export function parseJiraStory(raw: string): ParsedJiraStory {
  const lines = raw.split("\n");

  // Title: first line matching "Title: <text>"
  let title = "";
  for (const line of lines) {
    const m = line.match(/^Title:\s*(.+)/i);
    if (m) {
      title = m[1].trim();
      break;
    }
  }

  // Map section headers to keys
  const HEADERS: Record<string, string> = {
    "user story:":          "userStory",
    "user stories:":        "userStory",
    "context:":             "context",
    "acceptance criteria:": "acceptanceCriteria",
  };

  const sections: Record<string, string[]> = {};
  let current: string | null = null;

  for (const line of lines) {
    const normalized = line.trim().toLowerCase();
    const matched = Object.keys(HEADERS).find((h) => normalized === h);
    if (matched) {
      current = HEADERS[matched];
      sections[current] ??= [];
    } else if (current) {
      sections[current].push(line);
    }
  }

  const joinSection = (name: string) =>
    (sections[name] ?? [])
      .map((l) => l.trim())
      .filter(Boolean)
      .join(" ")
      .trim();

  const acceptanceCriteria = (sections.acceptanceCriteria ?? [])
    .map((l) => l.trim())
    .filter((l) => /^[-•*]/.test(l))
    .map((l) => l.replace(/^[-•*]\s*/, "").trim())
    .filter(Boolean);

  return {
    title,
    userStory: joinSection("userStory"),
    context: joinSection("context"),
    acceptanceCriteria,
  };
}
