-- Three structured callout fields generated by synthesis (v3.5).
-- All nullable — synthesis returns null when a callout genuinely doesn't apply.
-- No manual_* overrides in v1 — synthesized-only.
ALTER TABLE ideas
  ADD COLUMN why_callout                TEXT,
  ADD COLUMN customers_prospects_callout TEXT,
  ADD COLUMN hard_deadline_notes_callout TEXT;
